### PR TITLE
Aux directories get created in the wrong place

### PR DESCRIPTION
**Pull request by sixhobbits**
With the current instructions in the README, you are told to call make aux_dirs, which calls this script. The directories are all then created two levels too high in the tree, as they are created relative to the main directory.

### CODE REVIEW

**Comment by nelson-liu** [comment]
thanks for the PR! 

Interestingly, I've specifically tried to fix this before but I guess I failed. Which OS are you running? I had this issue before and I specifically tried to use `https://github.com/sixhobbits/paraphrase-id-tensorflow/blob/master/scripts/data/make_auxiliary_dirs.sh#L2` to try to CD to a consistent place across machines (the path of the script), so you should remove that.

Alternatively, I think a cleaner solution might be to just have the code in the actual makefile itself?

What do you think?

**Comment by nelson-liu** [comment]
eh after thinking about it more, i think it's easiest to just remove the explicit CD currently in the file and add a warning that the proper way to run the script is through `make` as opposed to just running the script directly...

**Comment by nelson-liu** [comment]
Thanks for the help @sixhobbits , I hope you don't mind me finishing up this PR for you (seems like a pretty major setup bug to me, so thanks for catching it)

**Comment by sixhobbits** [comment]
Thanks for fixing! Maybe a python setup script could be more consistent? You can get the directory of the script itself with os.path(__file__) or something and do everything relative to their so it doesn't matter where people run it from

**Comment by sixhobbits** [comment]
But pretty sure this fixes for large majority so maybe not worth the effort.

**Comment by nelson-liu** [comment]
That's a great idea, but yeah it isn't the top priority for me right now. I've put it on the issue tracker and marked it as "contributions welcome". Thanks for the suggestion @sixhobbits !

**Pull request merged**
